# This file is used by .github/workflows/pr-labeler.yml to label pull requests based on the files changed in the PR.
CI:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

system:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - yarn.lock
          - .vscode/**
          - scripts/**
          - tests/**
          - jest.config.json

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
