name: Auto-approve PR
on:
  workflow_call:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Approve Renovate PR
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          review-message: "I'm **approving** this PR because it includes a patch or minor update. Thanks!"
          github-token: ${{ secrets.GITHUB_TOKEN }}
