# **Name**
# PR labeler - Reusable workflow

# **Overview**
# This workflow labels pull-requests based on the content and path of the files.

# **When**
# This workflow is triggered by other workflows.
# It is not triggered by any events.

name: PR labeler
on:
  workflow_call:

# Define the jobs that are called by other workflows.
jobs:
  triage:
    name: "Label PRs"
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      # Uploads repository content to the runner
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          repository: "palashmon/reusable-workflows"
      - name: Add labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          configuration-path: .github/workflows/config/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
