# **Name**
# Publish NPM Release - Reusable workflow

# **Overview**
# This workflow tests the project and then
# publishes a new release to the NPM registry.

# **When**
# This workflow is triggered by other workflows.
# It is not triggered by any events.

name: Publish NPM Release
on:
  workflow_call:
    inputs:
      build-needed:
        description: "Set to true if the build step is needed."
        required: false
        type: boolean
        default: false

# Define the jobs that are called by other workflows.
jobs:
  check_date:
    name: Check latest commit
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: "Debug: Print latest commit"
        run: |
          echo ${{ github.sha }}
          echo $(git rev-list  --after="6 days" --max-count=1  ${{ github.sha }})
      - id: should_run
        continue-on-error: true
        name: Check if release is needed
        run: |
          set -x
          if test -z $(git rev-list  --after="6 days" --max-count=1  ${{ github.sha }}) ; then
            should_run=false
          else
            should_run=true
          fi
          echo "should_run=$should_run"
          echo "should_run=$should_run" >> $GITHUB_OUTPUT

  test:
    name: "Test: Node 20"
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set Node version to 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  publish:
    name: "Publish to NPM"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set Node version to 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm install
      - name: Build
        if: ${{ inputs.build-needed == true }}
        run: |
          echo "Build needed: ${{ inputs.build-needed }}"
          npm run build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
