# **Name**
# Publish NPM Release - Reusable workflow

# **Overview**
# This workflow tests the project and then
# publishes a new release to the NPM registry.

# **When**
# This workflow is triggered by other workflows.
# It is not triggered by any events.

name: Publish NPM Release
on:
  workflow_call:
    inputs:
      build-needed:
        description: "Set to true if the build step is needed."
        required: false
        type: boolean
        default: false

# Define the jobs that are called by other workflows.
jobs:
  test:
    name: "Test: Node 20"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Set Node version to 20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  publish:
    name: "Publish to NPM"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Set Node version to 20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm install
      - name: Build
        if: ${{ inputs.build-needed == true }}
        run: |
          echo "Build needed: ${{ inputs.build-needed }}"
          npm run build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
