# **Name**
# Should Run - Reusable workflow

# **Overview**
# This workflow check if a fresh commit is available

# **When**
# Mainly, this workflow is called by other workflows.

name: Should Run
on:
  workflow_call:

# Define the jobs that are called by other workflows.
jobs:
  # Check if a fresh commit is available
  check_date:
    name: Check latest commit
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: "Debug: Print latest commit"
        run: |
          echo ${{ github.sha }}
          echo $(git rev-list  --after="6 days" --max-count=1  ${{ github.sha }})

      - id: should_run
        continue-on-error: true
        name: Check if release is needed
        run: |
          set -x
          if test -z $(git rev-list  --after="6 days" --max-count=1  ${{ github.sha }}) ; then
            should_run=false
          else
            should_run=true
          fi
          echo "should_run=$should_run"
          echo "should_run=$should_run" >> $GITHUB_OUTPUT
