# **Name**
# Mark stale issues and PR - Reusable workflow

# **Overview**
# This workflow marks issues and PRs as stale if they have been inactive for a year.

# **When**
# This workflow is triggered by other workflows.
# It is not triggered by any events.

name: Mark stale issues and PR
on:
  workflow_call:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 365
        stale-issue-message: 'Hi! This issue has been inactive for a year now. Could you please remove the `stale` label or comment? Otherwise, we may have to close it in 7 days. Thank you!'
        stale-pr-message: 'Hi! This PR has been inactive for a year now. Could you please remove the `stale` label or comment? Otherwise, we may have to close it in 7 days. Thank you!'
        close-issue-message: 'Hi there! This issue was closed due to inactivity for 7 days. If you have any updates or would like to reopen it, feel free to do so. Thanks!'
        close-pr-message: 'Hi there! This PR was closed due to inactivity for 7 days. If you have any updates or would like to reopen it, feel free to do so. Thanks!'
        exempt-issue-labels: 'help wanted, good first issue, never gets stale'
        exempt-pr-labels: 'help wanted, never gets stale'